---

- name: Install Hyprland and core packages
  pacman:
    name: "{{ hyprland_packages }}"
    state: present
    update_cache: true

- name: Install GPU-specific packages
  pacman:
    name: "{{ gpu_packages[ansible_facts['vendor'] | default('intel')] }}"
    state: present

- name: Install additional system packages
  pacman:
    name: "{{ additional_packages }}"
    state: present

- name: Enable and start NetworkManager service
  systemd:
    name: NetworkManager
    enabled: true
    state: started

- name: Enable and start SDDM service
  systemd:
    name: sddm
    enabled: true
    state: started

- name: Enable seatd service for hardware access
  systemd:
    name: seatd
    enabled: true
    state: started

- name: Create Hyprland configuration directory
  file:
    path: ~/.config/hypr
    state: directory
    mode: '0755'

- name: Copy Hyprland default configuration
  copy:
    src: /usr/share/hyprland/hyprland.conf.example
    dest: ~/.config/hypr/hyprland.conf
    remote_src: true

- name: Set SDDM theme
  lineinfile:
    path: /etc/sddm.conf
    line: "Current=arc-dark"
    create: yes

- name: Display success message
  debug:
    msg: "Hyprland setup complete! Configure it at ~/.config/hypr/hyprland.conf."
